dictionary IdleOptions {
  [EnforceRange] unsigned long threshold = 60000;
};

enum UserIdleState {
    "active",
    "idle"
};

enum ScreenIdleState {
    "locked",
    "unlocked"
};

[
  SecureContext,
  Constructor(optional IdleOptions options),
  Exposed=(Window,Worker)
] interface IdleDetector : EventTarget {
  readonly attribute UserIdleState? userState;
  readonly attribute ScreenIdleState? screenState;
  attribute EventHandler onchange;
  Promise<any> start();
  void stop();
};
